version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Optionally configure security-only to true if you want only security fixes:
    # allow:
    #   - dependency-type: "direct"
    #   - dependency-type: "indirect"
    # You can also configure labels:
    labels:
      - "dependencies"
      - "automerge:disabled"
