name: Documentation Deployment

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies (if docs require build)
        run: |
          if [ -f package.json ]; then
            npm ci || true
          fi

      - name: Build docs (if build script exists)
        run: |
          if npm run | grep -q build:docs; then
            npm run build:docs
          elif [ -d docs ]; then
            echo "No build step detected — publishing docs folder directly"
          else
            echo "No docs directory found — nothing to publish"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
